export const dummyProducts = [
    {
        product_id: 1,
        name: 'Lorem',
        product_type : 'bestseller',
        description:'nailsLorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
        price:30,
        discounted_price_percentage:125,
        rating: 4.5,
        product_imgs_id: '/image/wrapper/stockpolish.png',
        category : 'nails',
    },
    {
        product_id: 2,
        name: 'Ipsum',
        product_type : 'newproduct',
        description:'manicure Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
        price:35,
        discounted_price_percentage:25,
        rating: 4,
        product_imgs_id: '/image/wrapper/stockpolish.png',
        category : 'manicure',
    },
    {
        product_id: 3,
        name: 'Silor',
        product_type : 'none',
        description:'pedicure Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
        price:40,
        discounted_price_percentage:525,
        rating: 3.5,
        product_imgs_id: '/image/wrapper/stockpolish.png',
        category : 'pedicure',
    },
]